### ISSUE TITLE
Start Using WebRTC

### ISSUE THREAD

**Issue by georgeaf99** [xuset/p2pweb#1]
We need to move over from the centralized server protocol using _socket.io_ to WebRTC

**Comment by xuset** [comment]
[simple-peer](https://github.com/feross/simple-peer) will be a good package to use since it simplifies a lot of the complexity of webrtc.

If you haven't already, [this](http://www.html5rocks.com/en/tutorials/webrtc/basics/) is a good intro into webrtc

**Comment by xuset** [comment]
Closed in fa7938868ff4bcc1a0b72c6bee3c3cc77a0b775b
